### PR TITLE
[osx][android] cache CMAKE_OBJDUMP & CMAKE_RANLIB

### PR DESCRIPTION
**Pull request by Rechi**
otherwise these settings are not honored during configuring kodi

### CODE REVIEW

**Comment by Rechi** [comment]
@Memphiz ping

**Comment by Memphiz** [comment]
Thx - any idea why it worked for me?

**Comment by Rechi** [comment]
have you checked you CMakeCache.txt if the settings where honoured?
For me one of them was set to `:` and it therefore acts relay strange.
It called ccache with `:` as second argument (normally compiler) and obviously it didn't work.

**Comment by Memphiz** [comment]
Well i need to check - but as this whole thing was a compile fix in the first place i doubt it would have worked at all if they were not set ...

**Pull request merged**
