### PR TITLE
Derive the app group ID from the main bundle ID

### PR DESCRIPTION
**Pull request by DanTheMan827**
@Memphiz This enables my iOS App Signer to properly sign the app with a working top shelf.

### CODE REVIEW

**Comment by Memphiz** [comment]
Great work - about to try it out in a min!

**Comment by Memphiz** [comment]
i hope its ok for you that this commit will be squashed down into the tvos platform file cpmmit on my next rebase? (i try to keep the whole branch ready to do a PR to mainline)

**Comment by DanTheMan827** [comment]
To use it with iOS app signer the provisioning profile has to have an app group named group.*.shared where * is the app id

So basically create the blank project, fix issue, go to capabilities, add an app group with that template and then resign (Xcode will have created duplicates though)

**Comment by DanTheMan827** [comment]
You could actually remove the .shared from the app group name, now that I think about it that would probably be simpler for the how to because it would just be group.appid

**Comment by Memphiz** [comment]
yep - adapted accordingly (last commit)

**Comment by Memphiz** [comment]
i also kicked a new jenkins build ... have to go now for a while - feel free to download it from the mirrors and try it out :)

**Comment by DanTheMan827** [comment]
I would do that but it's 4:13AM here ;)

Also, you seem to be stuck on using confluence for the skin... Is that a bug or a change in Kodi master?

And some binary addons are incompatible due to api change (pvr.wmc is an example)

**Comment by Memphiz** [comment]
stuck to confluence sounds like a bug ... the incompatible api is a "feature" of cooking in master while its heavily changed ;) ... go to bed i suggest ;)

**Comment by Memphiz** [comment]
I see what you mean - there is no "more" button in the skin selection anymore ... strange

**Comment by DanTheMan827** [comment]
There are also no skins in the repository and if you install a zip it doesn't change

IF you package a skin in the app and change the default setting it changes

But change back to confluence and you can't change back

I've only tested this with the estuary preview so...

**Comment by Memphiz** [comment]
Its the same on master - i verified it on osx a min ago ...

**Comment by Memphiz** [comment]
I confirmed the skin issue. We have switched to the krypton repo. ATM there is no compatible skin with the krypton API, thats why you can't get more.

**Pull request merged**
